context("toJSON zerovec")

test_that("Encoding Factor Objects", {
  expect_that(toJSON1(character()), is_identical_to("[]"))
  expect_that(toJSON1(logical()), is_identical_to("[]"))
  expect_that(toJSON1(complex()), is_identical_to("[]"))
  expect_that(toJSON1(complex(), complex="list"), is_identical_to("{\"real\":[],\"imaginary\":[]}"))
  expect_that(toJSON1(double()), is_identical_to("[]"))
  expect_that(toJSON1(integer()), is_identical_to("[]"))
  expect_that(toJSON1(list()), is_identical_to("[]"))
  expect_that(toJSON1(factor()), is_identical_to("[]"))
  expect_that(toJSON1(factor(levels=c("foo", "bar"))), is_identical_to("[]"))
  expect_that(toJSON1(matrix(nrow=0, ncol=0)), is_identical_to("[]"))
  expect_that(toJSON1(as.matrix(numeric())), is_identical_to("[]"))
  expect_that(toJSON1(data.frame()), is_identical_to("[]"))
  expect_that(toJSON1(data.frame(foo=vector())), is_identical_to("[]"))
  expect_that(toJSON1(data.frame(foo=vector(), bar=logical())), is_identical_to("[]"))
  expect_that(toJSON1(Sys.time()[0], POSIXt="string"), is_identical_to("[]"))
  expect_that(toJSON1(Sys.time()[0], POSIXt="epoch"), is_identical_to("[]"))
  expect_that(toJSON1(Sys.time()[0], POSIXt="mongo"), is_identical_to("[]"))
  expect_that(toJSON1(Sys.time()[0], POSIXt="ISO8601"), is_identical_to("[]"))
  expect_that(toJSON1(as.Date(Sys.time())[0], POSIXt="ISO8601"), is_identical_to("[]"))
});
